package com.orcafin.entity;

public enum TransactionGroup {
    ASSINATURAS,
    CONTAS_FIXAS_CASA,
    COMPRAS_PONTUAIS,
    DIVIDAS_PARCELAS,
    ALIMENTACAO_CASA,
    RESTAURANTES,
    FATURA_CARTAO,
    VALE_TRANSPORTE,
    VALE_ALIMENTACAO_REFEICAO,
    INVESTIMENTOS,
    CAIXINHAS,
    AJUSTES_ESTORNOS,
    TARIFAS_JUROS,
    OUTROS
}
